// <auto-generated>Generated from pinned WSDLs; pass consumer-validated payloads.</auto-generated>
#nullable enable
using System.Threading;
using System.Threading.Tasks;
using NetArcaWs.Multitenancy;
using NetArcaWs.Services;
using NetArcaWs.HealthChecks;

namespace NetArcaWs.Examples;

/// <summary>Typed forwarding adapters. The caller supplies validated request data; this catalog creates no incomplete DTOs and submits no operation itself.</summary>
public static class OperationExamples
{
    public static Task<global::NetArcaWs.Contracts.WsfeV1.FecaeSolicitarResponse> WsfeV1_FECAESolicitarAsync(IWsfev1Service service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.WsfeV1.FecaeSolicitar validatedRequest, CancellationToken cancellationToken = default) => service.FECAESolicitarAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.WsfeV1.FeCompTotXRequestResponse> WsfeV1_FECompTotXRequestAsync(IWsfev1Service service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.WsfeV1.FeCompTotXRequest validatedRequest, CancellationToken cancellationToken = default) => service.FECompTotXRequestAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.WsfeV1.FeDummyResponse> WsfeV1_FEDummyAsync(IWsfev1Service service, ArcaEnvironment environment, CancellationToken cancellationToken = default) => service.FEDummyAsync(environment, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.WsfeV1.FeCompUltimoAutorizadoResponse> WsfeV1_FECompUltimoAutorizadoAsync(IWsfev1Service service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.WsfeV1.FeCompUltimoAutorizado validatedRequest, CancellationToken cancellationToken = default) => service.FECompUltimoAutorizadoAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.WsfeV1.FeCompConsultarResponse> WsfeV1_FECompConsultarAsync(IWsfev1Service service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.WsfeV1.FeCompConsultar validatedRequest, CancellationToken cancellationToken = default) => service.FECompConsultarAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.WsfeV1.FecaeaRegInformativoResponse> WsfeV1_FECAEARegInformativoAsync(IWsfev1Service service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.WsfeV1.FecaeaRegInformativo validatedRequest, CancellationToken cancellationToken = default) => service.FECAEARegInformativoAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.WsfeV1.FecaeaSolicitarResponse> WsfeV1_FECAEASolicitarAsync(IWsfev1Service service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.WsfeV1.FecaeaSolicitar validatedRequest, CancellationToken cancellationToken = default) => service.FECAEASolicitarAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.WsfeV1.FecaeaSinMovimientoConsultarResponse> WsfeV1_FECAEASinMovimientoConsultarAsync(IWsfev1Service service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.WsfeV1.FecaeaSinMovimientoConsultar validatedRequest, CancellationToken cancellationToken = default) => service.FECAEASinMovimientoConsultarAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.WsfeV1.FecaeaSinMovimientoInformarResponse> WsfeV1_FECAEASinMovimientoInformarAsync(IWsfev1Service service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.WsfeV1.FecaeaSinMovimientoInformar validatedRequest, CancellationToken cancellationToken = default) => service.FECAEASinMovimientoInformarAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.WsfeV1.FecaeaConsultarResponse> WsfeV1_FECAEAConsultarAsync(IWsfev1Service service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.WsfeV1.FecaeaConsultar validatedRequest, CancellationToken cancellationToken = default) => service.FECAEAConsultarAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.WsfeV1.FeParamGetCotizacionResponse> WsfeV1_FEParamGetCotizacionAsync(IWsfev1Service service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.WsfeV1.FeParamGetCotizacion validatedRequest, CancellationToken cancellationToken = default) => service.FEParamGetCotizacionAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.WsfeV1.FeParamGetTiposTributosResponse> WsfeV1_FEParamGetTiposTributosAsync(IWsfev1Service service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.WsfeV1.FeParamGetTiposTributos validatedRequest, CancellationToken cancellationToken = default) => service.FEParamGetTiposTributosAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.WsfeV1.FeParamGetTiposMonedasResponse> WsfeV1_FEParamGetTiposMonedasAsync(IWsfev1Service service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.WsfeV1.FeParamGetTiposMonedas validatedRequest, CancellationToken cancellationToken = default) => service.FEParamGetTiposMonedasAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.WsfeV1.FeParamGetTiposIvaResponse> WsfeV1_FEParamGetTiposIvaAsync(IWsfev1Service service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.WsfeV1.FeParamGetTiposIva validatedRequest, CancellationToken cancellationToken = default) => service.FEParamGetTiposIvaAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.WsfeV1.FeParamGetTiposOpcionalResponse> WsfeV1_FEParamGetTiposOpcionalAsync(IWsfev1Service service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.WsfeV1.FeParamGetTiposOpcional validatedRequest, CancellationToken cancellationToken = default) => service.FEParamGetTiposOpcionalAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.WsfeV1.FeParamGetTiposConceptoResponse> WsfeV1_FEParamGetTiposConceptoAsync(IWsfev1Service service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.WsfeV1.FeParamGetTiposConcepto validatedRequest, CancellationToken cancellationToken = default) => service.FEParamGetTiposConceptoAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.WsfeV1.FeParamGetPtosVentaResponse> WsfeV1_FEParamGetPtosVentaAsync(IWsfev1Service service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.WsfeV1.FeParamGetPtosVenta validatedRequest, CancellationToken cancellationToken = default) => service.FEParamGetPtosVentaAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.WsfeV1.FeParamGetTiposCbteResponse> WsfeV1_FEParamGetTiposCbteAsync(IWsfev1Service service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.WsfeV1.FeParamGetTiposCbte validatedRequest, CancellationToken cancellationToken = default) => service.FEParamGetTiposCbteAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.WsfeV1.FeParamGetCondicionIvaReceptorResponse> WsfeV1_FEParamGetCondicionIvaReceptorAsync(IWsfev1Service service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.WsfeV1.FeParamGetCondicionIvaReceptor validatedRequest, CancellationToken cancellationToken = default) => service.FEParamGetCondicionIvaReceptorAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.WsfeV1.FeParamGetTiposDocResponse> WsfeV1_FEParamGetTiposDocAsync(IWsfev1Service service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.WsfeV1.FeParamGetTiposDoc validatedRequest, CancellationToken cancellationToken = default) => service.FEParamGetTiposDocAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.WsfeV1.FeParamGetTiposPaisesResponse> WsfeV1_FEParamGetTiposPaisesAsync(IWsfev1Service service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.WsfeV1.FeParamGetTiposPaises validatedRequest, CancellationToken cancellationToken = default) => service.FEParamGetTiposPaisesAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.WsfeV1.FeParamGetActividadesResponse> WsfeV1_FEParamGetActividadesAsync(IWsfev1Service service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.WsfeV1.FeParamGetActividades validatedRequest, CancellationToken cancellationToken = default) => service.FEParamGetActividadesAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.WsfexV1.FexAuthorizeResponse> WsfexV1_FEXAuthorizeAsync(IWsfexv1Service service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.WsfexV1.FexAuthorize validatedRequest, CancellationToken cancellationToken = default) => service.FEXAuthorizeAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.WsfexV1.FexGetCmpResponse2> WsfexV1_FEXGetCMPAsync(IWsfexv1Service service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.WsfexV1.FexGetCmp validatedRequest, CancellationToken cancellationToken = default) => service.FEXGetCMPAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.WsfexV1.FexGetParamCbteTipoResponse> WsfexV1_FEXGetPARAM_Cbte_TipoAsync(IWsfexv1Service service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.WsfexV1.FexGetParamCbteTipo validatedRequest, CancellationToken cancellationToken = default) => service.FEXGetPARAM_Cbte_TipoAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.WsfexV1.FexGetParamTipoExpoResponse> WsfexV1_FEXGetPARAM_Tipo_ExpoAsync(IWsfexv1Service service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.WsfexV1.FexGetParamTipoExpo validatedRequest, CancellationToken cancellationToken = default) => service.FEXGetPARAM_Tipo_ExpoAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.WsfexV1.FexGetParamIncotermsResponse> WsfexV1_FEXGetPARAM_IncotermsAsync(IWsfexv1Service service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.WsfexV1.FexGetParamIncoterms validatedRequest, CancellationToken cancellationToken = default) => service.FEXGetPARAM_IncotermsAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.WsfexV1.FexGetParamIdiomasResponse> WsfexV1_FEXGetPARAM_IdiomasAsync(IWsfexv1Service service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.WsfexV1.FexGetParamIdiomas validatedRequest, CancellationToken cancellationToken = default) => service.FEXGetPARAM_IdiomasAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.WsfexV1.FexGetParamUMedResponse> WsfexV1_FEXGetPARAM_UMedAsync(IWsfexv1Service service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.WsfexV1.FexGetParamUMed validatedRequest, CancellationToken cancellationToken = default) => service.FEXGetPARAM_UMedAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.WsfexV1.FexGetParamDstPaisResponse> WsfexV1_FEXGetPARAM_DST_paisAsync(IWsfexv1Service service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.WsfexV1.FexGetParamDstPais validatedRequest, CancellationToken cancellationToken = default) => service.FEXGetPARAM_DST_paisAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.WsfexV1.FexGetParamDstCuitResponse> WsfexV1_FEXGetPARAM_DST_CUITAsync(IWsfexv1Service service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.WsfexV1.FexGetParamDstCuit validatedRequest, CancellationToken cancellationToken = default) => service.FEXGetPARAM_DST_CUITAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.WsfexV1.FexGetParamMonResponse> WsfexV1_FEXGetPARAM_MONAsync(IWsfexv1Service service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.WsfexV1.FexGetParamMon validatedRequest, CancellationToken cancellationToken = default) => service.FEXGetPARAM_MONAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.WsfexV1.FexGetParamMonConCotizacionResponse> WsfexV1_FEXGetPARAM_MON_CON_COTIZACIONAsync(IWsfexv1Service service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.WsfexV1.FexGetParamMonConCotizacion validatedRequest, CancellationToken cancellationToken = default) => service.FEXGetPARAM_MON_CON_COTIZACIONAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.WsfexV1.FexGetLastCmpResponse> WsfexV1_FEXGetLast_CMPAsync(IWsfexv1Service service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.WsfexV1.FexGetLastCmp validatedRequest, CancellationToken cancellationToken = default) => service.FEXGetLast_CMPAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.WsfexV1.FexDummyResponse> WsfexV1_FEXDummyAsync(IWsfexv1Service service, ArcaEnvironment environment, CancellationToken cancellationToken = default) => service.FEXDummyAsync(environment, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.WsfexV1.FexGetParamCtzResponse> WsfexV1_FEXGetPARAM_CtzAsync(IWsfexv1Service service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.WsfexV1.FexGetParamCtz validatedRequest, CancellationToken cancellationToken = default) => service.FEXGetPARAM_CtzAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.WsfexV1.FexGetLastIdResponse> WsfexV1_FEXGetLast_IDAsync(IWsfexv1Service service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.WsfexV1.FexGetLastId validatedRequest, CancellationToken cancellationToken = default) => service.FEXGetLast_IDAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.WsfexV1.FexGetParamPtoVentaResponse> WsfexV1_FEXGetPARAM_PtoVentaAsync(IWsfexv1Service service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.WsfexV1.FexGetParamPtoVenta validatedRequest, CancellationToken cancellationToken = default) => service.FEXGetPARAM_PtoVentaAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.WsfexV1.FexCheckPermisoResponse> WsfexV1_FEXCheck_PermisoAsync(IWsfexv1Service service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.WsfexV1.FexCheckPermiso validatedRequest, CancellationToken cancellationToken = default) => service.FEXCheck_PermisoAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.WsfexV1.FexGetParamOpcionalesResponse> WsfexV1_FEXGetPARAM_OpcionalesAsync(IWsfexv1Service service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.WsfexV1.FexGetParamOpcionales validatedRequest, CancellationToken cancellationToken = default) => service.FEXGetPARAM_OpcionalesAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.WsfexV1.FexGetParamActividadesResponse> WsfexV1_FEXGetPARAM_ActividadesAsync(IWsfexv1Service service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.WsfexV1.FexGetParamActividades validatedRequest, CancellationToken cancellationToken = default) => service.FEXGetPARAM_ActividadesAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wsmtxca.DummyResponseType> Wsmtxca_dummyAsync(IWsmtxcav1Service service, ArcaEnvironment environment, CancellationToken cancellationToken = default) => service.dummyAsync(environment, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wsmtxca.AutorizarComprobanteResponseType> Wsmtxca_autorizarComprobanteAsync(IWsmtxcav1Service service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wsmtxca.AutorizarComprobanteRequestType validatedRequest, CancellationToken cancellationToken = default) => service.autorizarComprobanteAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wsmtxca.SolicitarCaeaResponseType> Wsmtxca_solicitarCAEAAsync(IWsmtxcav1Service service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wsmtxca.SolicitarCaeaRequestType validatedRequest, CancellationToken cancellationToken = default) => service.solicitarCAEAAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wsmtxca.InformarComprobanteCaeaResponseType> Wsmtxca_informarComprobanteCAEAAsync(IWsmtxcav1Service service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wsmtxca.InformarComprobanteCaeaRequestType validatedRequest, CancellationToken cancellationToken = default) => service.informarComprobanteCAEAAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wsmtxca.ConsultarUltimoComprobanteAutorizadoResponseType> Wsmtxca_consultarUltimoComprobanteAutorizadoAsync(IWsmtxcav1Service service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wsmtxca.ConsultarUltimoComprobanteAutorizadoRequestType validatedRequest, CancellationToken cancellationToken = default) => service.consultarUltimoComprobanteAutorizadoAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wsmtxca.ConsultarComprobanteResponseType> Wsmtxca_consultarComprobanteAsync(IWsmtxcav1Service service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wsmtxca.ConsultarComprobanteRequestType validatedRequest, CancellationToken cancellationToken = default) => service.consultarComprobanteAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wsmtxca.ConsultarTiposComprobanteResponseType> Wsmtxca_consultarTiposComprobanteAsync(IWsmtxcav1Service service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wsmtxca.ConsultarTiposComprobanteRequestType validatedRequest, CancellationToken cancellationToken = default) => service.consultarTiposComprobanteAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wsmtxca.ConsultarTiposDocumentoResponseType> Wsmtxca_consultarTiposDocumentoAsync(IWsmtxcav1Service service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wsmtxca.ConsultarTiposDocumentoRequestType validatedRequest, CancellationToken cancellationToken = default) => service.consultarTiposDocumentoAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wsmtxca.ConsultarAlicuotasIvaResponseType> Wsmtxca_consultarAlicuotasIVAAsync(IWsmtxcav1Service service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wsmtxca.ConsultarAlicuotasIvaRequestType validatedRequest, CancellationToken cancellationToken = default) => service.consultarAlicuotasIVAAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wsmtxca.ConsultarCondicionesIvaResponseType> Wsmtxca_consultarCondicionesIVAAsync(IWsmtxcav1Service service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wsmtxca.ConsultarCondicionesIvaRequestType validatedRequest, CancellationToken cancellationToken = default) => service.consultarCondicionesIVAAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wsmtxca.ConsultarMonedasResponseType> Wsmtxca_consultarMonedasAsync(IWsmtxcav1Service service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wsmtxca.ConsultarMonedasRequestType validatedRequest, CancellationToken cancellationToken = default) => service.consultarMonedasAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wsmtxca.ConsultarCotizacionMonedaResponseType> Wsmtxca_consultarCotizacionMonedaAsync(IWsmtxcav1Service service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wsmtxca.ConsultarCotizacionMonedaRequestType validatedRequest, CancellationToken cancellationToken = default) => service.consultarCotizacionMonedaAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wsmtxca.ConsultarUnidadesMedidaResponseType> Wsmtxca_consultarUnidadesMedidaAsync(IWsmtxcav1Service service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wsmtxca.ConsultarUnidadesMedidaRequestType validatedRequest, CancellationToken cancellationToken = default) => service.consultarUnidadesMedidaAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wsmtxca.ConsultarTiposTributoResponseType> Wsmtxca_consultarTiposTributoAsync(IWsmtxcav1Service service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wsmtxca.ConsultarTiposTributoRequestType validatedRequest, CancellationToken cancellationToken = default) => service.consultarTiposTributoAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wsmtxca.ConsultarPuntosVentaResponse> Wsmtxca_consultarPuntosVentaAsync(IWsmtxcav1Service service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wsmtxca.ConsultarPuntosVentaRequestType validatedRequest, CancellationToken cancellationToken = default) => service.consultarPuntosVentaAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wsmtxca.ConsultarPuntosVentaCaeResponse> Wsmtxca_consultarPuntosVentaCAEAsync(IWsmtxcav1Service service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wsmtxca.ConsultarPuntosVentaCaeRequestType validatedRequest, CancellationToken cancellationToken = default) => service.consultarPuntosVentaCAEAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wsmtxca.ConsultarPuntosVentaCaeaResponse> Wsmtxca_consultarPuntosVentaCAEAAsync(IWsmtxcav1Service service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wsmtxca.ConsultarPuntosVentaCaeaRequestType validatedRequest, CancellationToken cancellationToken = default) => service.consultarPuntosVentaCAEAAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wsmtxca.InformarCaeaNoUtilizadoResponseType> Wsmtxca_informarCAEANoUtilizadoAsync(IWsmtxcav1Service service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wsmtxca.InformarCaeaNoUtilizadoRequestType validatedRequest, CancellationToken cancellationToken = default) => service.informarCAEANoUtilizadoAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wsmtxca.InformarCaeaNoUtilizadoPtoVtaResponseType> Wsmtxca_informarCAEANoUtilizadoPtoVtaAsync(IWsmtxcav1Service service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wsmtxca.InformarCaeaNoUtilizadoPtoVtaRequestType validatedRequest, CancellationToken cancellationToken = default) => service.informarCAEANoUtilizadoPtoVtaAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wsmtxca.ConsultarPtosVtaCaeaNoInformadosResponseType> Wsmtxca_consultarPtosVtaCAEANoInformadosAsync(IWsmtxcav1Service service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wsmtxca.ConsultarPtosVtaCaeaNoInformadosRequestType validatedRequest, CancellationToken cancellationToken = default) => service.consultarPtosVtaCAEANoInformadosAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wsmtxca.ConsultarCaeaResponseType> Wsmtxca_consultarCAEAAsync(IWsmtxcav1Service service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wsmtxca.ConsultarCaeaRequestType validatedRequest, CancellationToken cancellationToken = default) => service.consultarCAEAAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wsmtxca.ConsultarCaeaEntreFechasResponseType> Wsmtxca_consultarCAEAEntreFechasAsync(IWsmtxcav1Service service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wsmtxca.ConsultarCaeaEntreFechasRequestType validatedRequest, CancellationToken cancellationToken = default) => service.consultarCAEAEntreFechasAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wsmtxca.AutorizarAjusteIvaResponseType> Wsmtxca_autorizarAjusteIVAAsync(IWsmtxcav1Service service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wsmtxca.AutorizarAjusteIvaRequestType validatedRequest, CancellationToken cancellationToken = default) => service.autorizarAjusteIVAAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wsmtxca.InformarAjusteIvacaeaResponseType> Wsmtxca_informarAjusteIVACAEAAsync(IWsmtxcav1Service service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wsmtxca.InformarAjusteIvacaeaRequestType validatedRequest, CancellationToken cancellationToken = default) => service.informarAjusteIVACAEAAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wsmtxca.ConsultarTiposDatosAdicionalesResponseType> Wsmtxca_consultarTiposDatosAdicionalesAsync(IWsmtxcav1Service service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wsmtxca.ConsultarTiposDatosAdicionalesRequestType validatedRequest, CancellationToken cancellationToken = default) => service.consultarTiposDatosAdicionalesAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wsmtxca.ConsultarActividadesVigentesResponseType> Wsmtxca_consultarActividadesVigentesAsync(IWsmtxcav1Service service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wsmtxca.ConsultarActividadesVigentesRequestType validatedRequest, CancellationToken cancellationToken = default) => service.consultarActividadesVigentesAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wsmtxca.ConsultarCondicionesIvaReceptorResponseType> Wsmtxca_consultarCondicionesIVAReceptorAsync(IWsmtxcav1Service service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wsmtxca.ConsultarCondicionesIvaReceptorRequestType validatedRequest, CancellationToken cancellationToken = default) => service.consultarCondicionesIVAReceptorAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wscdc.ComprobantesModalidadConsultarResponse> Wscdc_ComprobantesModalidadConsultarAsync(IWscdcService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wscdc.ComprobantesModalidadConsultar validatedRequest, CancellationToken cancellationToken = default) => service.ComprobantesModalidadConsultarAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wscdc.ComprobantesTipoConsultarResponse> Wscdc_ComprobantesTipoConsultarAsync(IWscdcService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wscdc.ComprobantesTipoConsultar validatedRequest, CancellationToken cancellationToken = default) => service.ComprobantesTipoConsultarAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wscdc.DocumentosTipoConsultarResponse> Wscdc_DocumentosTipoConsultarAsync(IWscdcService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wscdc.DocumentosTipoConsultar validatedRequest, CancellationToken cancellationToken = default) => service.DocumentosTipoConsultarAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wscdc.OpcionalesTipoConsultarResponse> Wscdc_OpcionalesTipoConsultarAsync(IWscdcService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wscdc.OpcionalesTipoConsultar validatedRequest, CancellationToken cancellationToken = default) => service.OpcionalesTipoConsultarAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wscdc.ComprobanteConstatarResponse> Wscdc_ComprobanteConstatarAsync(IWscdcService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wscdc.ComprobanteConstatar validatedRequest, CancellationToken cancellationToken = default) => service.ComprobanteConstatarAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wscdc.ComprobanteDummyResponse> Wscdc_ComprobanteDummyAsync(IWscdcService service, ArcaEnvironment environment, CancellationToken cancellationToken = default) => service.ComprobanteDummyAsync(environment, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.WsfeCred.DummyResponseType> WsfeCred_dummyAsync(IWsfecredService service, ArcaEnvironment environment, CancellationToken cancellationToken = default) => service.dummyAsync(environment, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.WsfeCred.ConsultarComprobantesResponseType> WsfeCred_consultarComprobantesAsync(IWsfecredService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.WsfeCred.ConsultarComprobanteRequestType validatedRequest, CancellationToken cancellationToken = default) => service.consultarComprobantesAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.WsfeCred.RechazarNotaDcResponseType> WsfeCred_rechazarNotaDCAsync(IWsfecredService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.WsfeCred.RechazarNotaDcRequestType validatedRequest, CancellationToken cancellationToken = default) => service.rechazarNotaDCAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.WsfeCred.ConsultarCtasCtesResponseType> WsfeCred_consultarCtasCtesAsync(IWsfecredService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.WsfeCred.ConsultarCtasCtesRequestType validatedRequest, CancellationToken cancellationToken = default) => service.consultarCtasCtesAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.WsfeCred.ConsultarCtaCteResponseType> WsfeCred_consultarCtaCteAsync(IWsfecredService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.WsfeCred.ConsultarCtaCteRequestType validatedRequest, CancellationToken cancellationToken = default) => service.consultarCtaCteAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.WsfeCred.InformarCancelacionTotalFeCredResponse> WsfeCred_informarCancelacionTotalFECredAsync(IWsfecredService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.WsfeCred.InformarCancelacionTotalFeCredRequestType validatedRequest, CancellationToken cancellationToken = default) => service.informarCancelacionTotalFECredAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.WsfeCred.AceptarFeCredResponse> WsfeCred_aceptarFECredAsync(IWsfecredService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.WsfeCred.AceptarFeCredRequestType validatedRequest, CancellationToken cancellationToken = default) => service.aceptarFECredAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.WsfeCred.RechazarFeCredResponse> WsfeCred_rechazarFECredAsync(IWsfecredService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.WsfeCred.RechazarFeCredRequestType validatedRequest, CancellationToken cancellationToken = default) => service.rechazarFECredAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.WsfeCred.InformarFacturaAgtDptoCltvResponse> WsfeCred_informarFacturaAgtDptoCltvAsync(IWsfecredService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.WsfeCred.InformarFacturaAgtDptoCltvRequestType validatedRequest, CancellationToken cancellationToken = default) => service.informarFacturaAgtDptoCltvAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.WsfeCred.ConsultarFacturasAgtDptoCltvResponseType> WsfeCred_consultarFacturasAgtDptoCltvAsync(IWsfecredService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.WsfeCred.ConsultarFacturasAgtDptoCltvRequestType validatedRequest, CancellationToken cancellationToken = default) => service.consultarFacturasAgtDptoCltvAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.WsfeCred.ConsultarCuentasEnAgtDptoCltvResponseType> WsfeCred_consultarCuentasEnAgtDptoCltvAsync(IWsfecredService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.WsfeCred.ConsultarCuentasEnAgtDptoCltvRequestType validatedRequest, CancellationToken cancellationToken = default) => service.consultarCuentasEnAgtDptoCltvAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.WsfeCred.ConsultarObligadoRecepcionResponseType> WsfeCred_consultarObligadoRecepcionAsync(IWsfecredService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.WsfeCred.ConsultarObligadoRecepcionRequestType validatedRequest, CancellationToken cancellationToken = default) => service.consultarObligadoRecepcionAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.WsfeCred.ConsultarTiposRetencionesResponseType> WsfeCred_consultarTiposRetencionesAsync(IWsfecredService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.WsfeCred.ConsultarTiposRetencionesRequest validatedRequest, CancellationToken cancellationToken = default) => service.consultarTiposRetencionesAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.WsfeCred.ConsultarTiposMotivosRechazoResponse> WsfeCred_consultarTiposMotivosRechazoAsync(IWsfecredService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.WsfeCred.ConsultarTiposMotivosRechazoRequest validatedRequest, CancellationToken cancellationToken = default) => service.consultarTiposMotivosRechazoAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.WsfeCred.ConsultarTiposFormasCancelacionResponse> WsfeCred_consultarTiposFormasCancelacionAsync(IWsfecredService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.WsfeCred.ConsultarTiposFormasCancelacionRequest validatedRequest, CancellationToken cancellationToken = default) => service.consultarTiposFormasCancelacionAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.WsfeCred.ObtenerRemitosResponseType> WsfeCred_obtenerRemitosAsync(IWsfecredService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.WsfeCred.ObtenerRemitosRequestType validatedRequest, CancellationToken cancellationToken = default) => service.obtenerRemitosAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.WsfeCred.ConsultarHistorialEstadosComprobanteResponseType> WsfeCred_consultarHistorialEstadosComprobanteAsync(IWsfecredService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.WsfeCred.ConsultarHistorialEstadosComprobanteRequestType validatedRequest, CancellationToken cancellationToken = default) => service.consultarHistorialEstadosComprobanteAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.WsfeCred.ConsultarHistorialEstadosCtaCteResponseType> WsfeCred_consultarHistorialEstadosCtaCteAsync(IWsfecredService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.WsfeCred.ConsultarHistorialEstadosCtaCteRequestType validatedRequest, CancellationToken cancellationToken = default) => service.consultarHistorialEstadosCtaCteAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.WsfeCred.ConsultarTiposAjustesOperacionResponse> WsfeCred_consultarTiposAjustesOperacionAsync(IWsfecredService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.WsfeCred.ConsultarTiposAjustesOperacionRequest validatedRequest, CancellationToken cancellationToken = default) => service.consultarTiposAjustesOperacionAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.WsfeCred.ConsultarMontoObligadoRecepcionResponseType> WsfeCred_consultarMontoObligadoRecepcionAsync(IWsfecredService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.WsfeCred.ConsultarMontoObligadoRecepcionRequestType validatedRequest, CancellationToken cancellationToken = default) => service.consultarMontoObligadoRecepcionAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.WsfeCred.ModificarOpcionTransferenciaResponse> WsfeCred_modificarOpcionTransferenciaAsync(IWsfecredService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.WsfeCred.ModificarOpcionTransferenciaRequestType validatedRequest, CancellationToken cancellationToken = default) => service.modificarOpcionTransferenciaAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wscpe.DummyResponse> Wscpe_dummyAsync(IWscpeService service, ArcaEnvironment environment, CancellationToken cancellationToken = default) => service.dummyAsync(environment, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wscpe.ConsultarProvinciasResponse> Wscpe_consultarProvinciasAsync(IWscpeService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wscpe.ConsultarProvinciasRequest validatedRequest, CancellationToken cancellationToken = default) => service.consultarProvinciasAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wscpe.ConsultarCategoriasSemillasResponse> Wscpe_consultarCategoriasSemillasAsync(IWscpeService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wscpe.ConsultarCategoriasSemillasRequest validatedRequest, CancellationToken cancellationToken = default) => service.consultarCategoriasSemillasAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wscpe.ConsultarVariedadesSemillasResponse> Wscpe_consultarVariedadesSemillasAsync(IWscpeService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wscpe.ConsultarVariedadesSemillasRequest validatedRequest, CancellationToken cancellationToken = default) => service.consultarVariedadesSemillasAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wscpe.ConsultarCpedgPendienteActivacionResponse> Wscpe_consultarCPEDGPendienteActivacionAsync(IWscpeService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wscpe.ConsultarCpedgPendienteActivacionRequest validatedRequest, CancellationToken cancellationToken = default) => service.consultarCPEDGPendienteActivacionAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wscpe.ConsultarCpeEmitidasDestinoDgPendientesActivacionResponse> Wscpe_consultarCPEEmitidasDestinoDGPendientesActivacionAsync(IWscpeService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wscpe.ConsultarCpeEmitidasDestinoDgPendientesActivacionRequest validatedRequest, CancellationToken cancellationToken = default) => service.consultarCPEEmitidasDestinoDGPendientesActivacionAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wscpe.ConsultarTiposEmbalajeResponse> Wscpe_consultarTiposEmbalajeAsync(IWscpeService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wscpe.ConsultarTiposEmbalajeRequest validatedRequest, CancellationToken cancellationToken = default) => service.consultarTiposEmbalajeAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wscpe.ConsultarUnidadesMedidaResponse> Wscpe_consultarUnidadesMedidaAsync(IWscpeService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wscpe.ConsultarUnidadesMedidaRequest validatedRequest, CancellationToken cancellationToken = default) => service.consultarUnidadesMedidaAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wscpe.ConsultarDerivadosGranariosResponse> Wscpe_consultarDerivadosGranariosAsync(IWscpeService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wscpe.ConsultarDerivadosGranariosRequest validatedRequest, CancellationToken cancellationToken = default) => service.consultarDerivadosGranariosAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wscpe.ConsultarLocalidadesPorProvinciaResponse> Wscpe_consultarLocalidadesPorProvinciaAsync(IWscpeService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wscpe.ConsultarLocalidadesPorProvinciaRequest validatedRequest, CancellationToken cancellationToken = default) => service.consultarLocalidadesPorProvinciaAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wscpe.ConsultarDomiciliosPorCuitResponse> Wscpe_consultarDomiciliosPorCUITAsync(IWscpeService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wscpe.ConsultarDomiciliosPorCuitRequest validatedRequest, CancellationToken cancellationToken = default) => service.consultarDomiciliosPorCUITAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wscpe.ConsultarLocalidadesProductorResponse> Wscpe_consultarLocalidadesProductorAsync(IWscpeService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wscpe.ConsultarLocalidadesProductorRequest validatedRequest, CancellationToken cancellationToken = default) => service.consultarLocalidadesProductorAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wscpe.ConsultarTiposGranoResponse> Wscpe_consultarTiposGranoAsync(IWscpeService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wscpe.ConsultarTiposGranoRequest validatedRequest, CancellationToken cancellationToken = default) => service.consultarTiposGranoAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wscpe.ConsultarUltNroOrdenResponse> Wscpe_consultarUltNroOrdenAsync(IWscpeService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wscpe.ConsultarUltNroOrdenRequest validatedRequest, CancellationToken cancellationToken = default) => service.consultarUltNroOrdenAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wscpe.InformarContingenciaResponse> Wscpe_informarContingenciaAsync(IWscpeService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wscpe.InformarContingenciaRequest validatedRequest, CancellationToken cancellationToken = default) => service.informarContingenciaAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wscpe.InformarContingenciaEmisionDestinoDgResponse> Wscpe_informarContingenciaEmisionDestinoDGAsync(IWscpeService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wscpe.InformarContingenciaEmisionDestinoDgRequest validatedRequest, CancellationToken cancellationToken = default) => service.informarContingenciaEmisionDestinoDGAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wscpe.AnularCpeResponse> Wscpe_anularCPEAsync(IWscpeService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wscpe.AnularCpeRequest validatedRequest, CancellationToken cancellationToken = default) => service.anularCPEAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wscpe.AnularCpeEmisionDestinoDgResponse> Wscpe_anularCPEEmisionDestinoDGAsync(IWscpeService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wscpe.AnularCpeEmisionDestinoDgRequest validatedRequest, CancellationToken cancellationToken = default) => service.anularCPEEmisionDestinoDGAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wscpe.ConfirmarArriboCpeResponse> Wscpe_confirmarArriboCPEAsync(IWscpeService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wscpe.ConfirmarArriboCpeRequest validatedRequest, CancellationToken cancellationToken = default) => service.confirmarArriboCPEAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wscpe.RechazoCpeResponse> Wscpe_rechazoCPEAsync(IWscpeService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wscpe.RechazoCpeRequest validatedRequest, CancellationToken cancellationToken = default) => service.rechazoCPEAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wscpe.DescargadoDestinoCpeResponse> Wscpe_descargadoDestinoCPEAsync(IWscpeService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wscpe.DescargadoDestinoCpeRequest validatedRequest, CancellationToken cancellationToken = default) => service.descargadoDestinoCPEAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wscpe.DescargadoDestinoCpeEmisionDestinoDgResponse> Wscpe_descargadoDestinoCPEEmisionDestinoDGAsync(IWscpeService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wscpe.DescargadoDestinoCpeEmisionDestinoDgRequest validatedRequest, CancellationToken cancellationToken = default) => service.descargadoDestinoCPEEmisionDestinoDGAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wscpe.AceptarEmisionDgResponse> Wscpe_aceptarEmisionDGAsync(IWscpeService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wscpe.AceptarEmisionDgRequest validatedRequest, CancellationToken cancellationToken = default) => service.aceptarEmisionDGAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wscpe.RechazarEmisionDgResp> Wscpe_rechazarEmisionDGAsync(IWscpeService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wscpe.RechazarEmisionDgRequest validatedRequest, CancellationToken cancellationToken = default) => service.rechazarEmisionDGAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wscpe.AceptarEmisionDestinoDgResponse> Wscpe_aceptarEmisionDestinoDGAsync(IWscpeService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wscpe.AceptarEmisionDestinoDgRequest validatedRequest, CancellationToken cancellationToken = default) => service.aceptarEmisionDestinoDGAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wscpe.RechazarEmisionDestinoDgResp> Wscpe_rechazarEmisionDestinoDGAsync(IWscpeService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wscpe.RechazarEmisionDestinoDgRequest validatedRequest, CancellationToken cancellationToken = default) => service.rechazarEmisionDestinoDGAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wscpe.ConsultarCpePorDestinoResponse> Wscpe_consultarCPEPorDestinoAsync(IWscpeService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wscpe.ConsultarCpePorDestinoRequest validatedRequest, CancellationToken cancellationToken = default) => service.consultarCPEPorDestinoAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wscpe.ConsultarCpepPendientesDeResolucionResponse> Wscpe_consultarCPEPPendientesDeResolucionAsync(IWscpeService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wscpe.ConsultarCpepPendientesDeResolucionRequest validatedRequest, CancellationToken cancellationToken = default) => service.consultarCPEPPendientesDeResolucionAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wscpe.CerrarContingenciaCpeResponse> Wscpe_cerrarContingenciaCPEAsync(IWscpeService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wscpe.CerrarContingenciaCpeRequest validatedRequest, CancellationToken cancellationToken = default) => service.cerrarContingenciaCPEAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wscpe.CerrarContingenciaCpeEmisionDestinoDgResponse> Wscpe_cerrarContingenciaCPEEmisionDestinoDGAsync(IWscpeService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wscpe.CerrarContingenciaCpeEmisionDestinoDgRequest validatedRequest, CancellationToken cancellationToken = default) => service.cerrarContingenciaCPEEmisionDestinoDGAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wscpe.ConsultarPlantasResponse> Wscpe_consultarPlantasAsync(IWscpeService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wscpe.ConsultarPlantasRequest validatedRequest, CancellationToken cancellationToken = default) => service.consultarPlantasAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wscpe.ConsultarPlantasDgResponse> Wscpe_consultarPlantasDGAsync(IWscpeService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wscpe.ConsultarPlantasDgRequest validatedRequest, CancellationToken cancellationToken = default) => service.consultarPlantasDGAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wscpe.AutorizarCpeFerroviariaResponse> Wscpe_autorizarCPEFerroviariaAsync(IWscpeService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wscpe.AutorizarCpeFerroviariaRequest validatedRequest, CancellationToken cancellationToken = default) => service.autorizarCPEFerroviariaAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wscpe.AutorizarCpeFerroviariaDgResponse> Wscpe_autorizarCPEFerroviariaDGAsync(IWscpeService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wscpe.AutorizarCpeFerroviariaDgRequest validatedRequest, CancellationToken cancellationToken = default) => service.autorizarCPEFerroviariaDGAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wscpe.ConsultarCpeFerroviariaResponse> Wscpe_consultarCPEFerroviariaAsync(IWscpeService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wscpe.ConsultarCpeFerroviariaRequest validatedRequest, CancellationToken cancellationToken = default) => service.consultarCPEFerroviariaAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wscpe.ConsultarCpeFerroviariaDgResponse> Wscpe_consultarCPEFerroviariaDGAsync(IWscpeService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wscpe.ConsultarCpeFerroviariaDgRequest validatedRequest, CancellationToken cancellationToken = default) => service.consultarCPEFerroviariaDGAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wscpe.ConsultarCpeAutomotorDgResponse> Wscpe_consultarCPEAutomotorDGAsync(IWscpeService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wscpe.ConsultarCpeAutomotorDgRequest validatedRequest, CancellationToken cancellationToken = default) => service.consultarCPEAutomotorDGAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wscpe.ConsultarCpeEmisionDestinoDgResponse> Wscpe_consultarCPEEmisionDestinoDGAsync(IWscpeService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wscpe.ConsultarCpeEmisionDestinoDgRequest validatedRequest, CancellationToken cancellationToken = default) => service.consultarCPEEmisionDestinoDGAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wscpe.ConsultarCpeDuctosResponse> Wscpe_consultarCPEDuctosAsync(IWscpeService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wscpe.ConsultarCpeDuctosRequest validatedRequest, CancellationToken cancellationToken = default) => service.consultarCPEDuctosAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wscpe.NuevoDestinoDestinatarioCpeFerroviariaResponse> Wscpe_nuevoDestinoDestinatarioCPEFerroviariaAsync(IWscpeService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wscpe.NuevoDestinoDestinatarioCpeFerroviariaRequest validatedRequest, CancellationToken cancellationToken = default) => service.nuevoDestinoDestinatarioCPEFerroviariaAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wscpe.NuevoDestinoDestinatarioCpeFerroviariaDgResponse> Wscpe_nuevoDestinoDestinatarioCPEFerroviariaDGAsync(IWscpeService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wscpe.NuevoDestinoDestinatarioCpeFerroviariaDgRequest validatedRequest, CancellationToken cancellationToken = default) => service.nuevoDestinoDestinatarioCPEFerroviariaDGAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wscpe.NuevoDestinoDestinatarioCpeAutomotorDgResponse> Wscpe_nuevoDestinoDestinatarioCPEAutomotorDGAsync(IWscpeService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wscpe.NuevoDestinoDestinatarioCpeAutomotorDgRequest validatedRequest, CancellationToken cancellationToken = default) => service.nuevoDestinoDestinatarioCPEAutomotorDGAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wscpe.NuevoDestinoDestinatarioCpeEmisionDestinoDgResponse> Wscpe_nuevoDestinoDestinatarioCPEEmisionDestinoDGAsync(IWscpeService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wscpe.NuevoDestinoDestinatarioCpeEmisionDestinoDgRequest validatedRequest, CancellationToken cancellationToken = default) => service.nuevoDestinoDestinatarioCPEEmisionDestinoDGAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wscpe.RegresoOrigenCpeFerroviariaResponse> Wscpe_regresoOrigenCPEFerroviariaAsync(IWscpeService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wscpe.RegresoOrigenCpeFerroviariaRequest validatedRequest, CancellationToken cancellationToken = default) => service.regresoOrigenCPEFerroviariaAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wscpe.DesvioCpeFerroviariaResponse> Wscpe_desvioCPEFerroviariaAsync(IWscpeService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wscpe.DesvioCpeFerroviariaRequest validatedRequest, CancellationToken cancellationToken = default) => service.desvioCPEFerroviariaAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wscpe.DesvioCpeFerroviariaDgResponse> Wscpe_desvioCPEFerroviariaDGAsync(IWscpeService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wscpe.DesvioCpeFerroviariaDgRequest validatedRequest, CancellationToken cancellationToken = default) => service.desvioCPEFerroviariaDGAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wscpe.DesvioCpeAutomotorDgResponse> Wscpe_desvioCPEAutomotorDGAsync(IWscpeService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wscpe.DesvioCpeAutomotorDgRequest validatedRequest, CancellationToken cancellationToken = default) => service.desvioCPEAutomotorDGAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wscpe.ConfirmacionDefinitivaCpeFerroviariaResponse> Wscpe_confirmacionDefinitivaCPEFerroviariaAsync(IWscpeService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wscpe.ConfirmacionDefinitivaCpeFerroviariaRequest validatedRequest, CancellationToken cancellationToken = default) => service.confirmacionDefinitivaCPEFerroviariaAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wscpe.ConfirmacionDefinitivaCpeFerroviariaDgResponse> Wscpe_confirmacionDefinitivaCPEFerroviariaDGAsync(IWscpeService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wscpe.ConfirmacionDefinitivaCpeFerroviariaDgRequest validatedRequest, CancellationToken cancellationToken = default) => service.confirmacionDefinitivaCPEFerroviariaDGAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wscpe.ConfirmacionDefinitivaCpeAutomotorDgResponse> Wscpe_confirmacionDefinitivaCPEAutomotorDGAsync(IWscpeService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wscpe.ConfirmacionDefinitivaCpeAutomotorDgRequest validatedRequest, CancellationToken cancellationToken = default) => service.confirmacionDefinitivaCPEAutomotorDGAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wscpe.ConfirmacionDefinitivaCpeDuctosDgResponse> Wscpe_confirmacionDefinitivaCPEDuctosDGAsync(IWscpeService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wscpe.ConfirmacionDefinitivaCpeDuctosDgRequest validatedRequest, CancellationToken cancellationToken = default) => service.confirmacionDefinitivaCPEDuctosDGAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wscpe.ConsultaCpeFerroviariaPorNroOperativoResponse> Wscpe_consultaCPEFerroviariaPorNroOperativoAsync(IWscpeService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wscpe.ConsultaCpeFerroviariaPorNroOperativoRequest validatedRequest, CancellationToken cancellationToken = default) => service.consultaCPEFerroviariaPorNroOperativoAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wscpe.EditarCpeFerroviariaResponse> Wscpe_editarCPEFerroviariaAsync(IWscpeService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wscpe.EditarCpeFerroviariaRequest validatedRequest, CancellationToken cancellationToken = default) => service.editarCPEFerroviariaAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wscpe.EditarCpedgFerroviariaResponse> Wscpe_editarCPEDGFerroviariaAsync(IWscpeService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wscpe.EditarCpedgFerroviariaRequest validatedRequest, CancellationToken cancellationToken = default) => service.editarCPEDGFerroviariaAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wscpe.EditarCpedgAutomotorResponse> Wscpe_editarCPEDGAutomotorAsync(IWscpeService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wscpe.EditarCpedgAutomotorRequest validatedRequest, CancellationToken cancellationToken = default) => service.editarCPEDGAutomotorAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wscpe.EditarCpedgDuctosResponse> Wscpe_editarCPEDGDuctosAsync(IWscpeService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wscpe.EditarCpedgDuctosRequest validatedRequest, CancellationToken cancellationToken = default) => service.editarCPEDGDuctosAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wscpe.EditarCpeConfirmadaFerroviariaResponse> Wscpe_editarCPEConfirmadaFerroviariaAsync(IWscpeService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wscpe.EditarCpeConfirmadaFerroviariaRequest validatedRequest, CancellationToken cancellationToken = default) => service.editarCPEConfirmadaFerroviariaAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wscpe.AutorizarCpeAutomotorResponse> Wscpe_autorizarCPEAutomotorAsync(IWscpeService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wscpe.AutorizarCpeAutomotorRequest validatedRequest, CancellationToken cancellationToken = default) => service.autorizarCPEAutomotorAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wscpe.AutorizarCpeAutomotorDgResponse> Wscpe_autorizarCPEAutomotorDGAsync(IWscpeService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wscpe.AutorizarCpeAutomotorDgRequest validatedRequest, CancellationToken cancellationToken = default) => service.autorizarCPEAutomotorDGAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wscpe.AutorizarCpeDuctosDgResponse> Wscpe_autorizarCPEDuctosDGAsync(IWscpeService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wscpe.AutorizarCpeDuctosDgRequest validatedRequest, CancellationToken cancellationToken = default) => service.autorizarCPEDuctosDGAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wscpe.AutorizarCpeEmisionDestinoDgResponse> Wscpe_autorizarCPEEmisionDestinoDGAsync(IWscpeService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wscpe.AutorizarCpeEmisionDestinoDgRequest validatedRequest, CancellationToken cancellationToken = default) => service.autorizarCPEEmisionDestinoDGAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wscpe.ConsultarCpeAutomotorResponse> Wscpe_consultarCPEAutomotorAsync(IWscpeService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wscpe.ConsultarCpeAutomotorRequest validatedRequest, CancellationToken cancellationToken = default) => service.consultarCPEAutomotorAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wscpe.NuevoDestinoDestinatarioCpeAutomotorResponse> Wscpe_nuevoDestinoDestinatarioCPEAutomotorAsync(IWscpeService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wscpe.NuevoDestinoDestinatarioCpeAutomotorRequest validatedRequest, CancellationToken cancellationToken = default) => service.nuevoDestinoDestinatarioCPEAutomotorAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wscpe.RegresoOrigenCpeAutomotorResponse> Wscpe_regresoOrigenCPEAutomotorAsync(IWscpeService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wscpe.RegresoOrigenCpeAutomotorRequest validatedRequest, CancellationToken cancellationToken = default) => service.regresoOrigenCPEAutomotorAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wscpe.RegresoOrigenCpeAutomotorDgResponse> Wscpe_regresoOrigenCPEAutomotorDGAsync(IWscpeService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wscpe.RegresoOrigenCpeAutomotorDgRequest validatedRequest, CancellationToken cancellationToken = default) => service.regresoOrigenCPEAutomotorDGAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wscpe.RegresoOrigenCpeFerroviariaDgResponse> Wscpe_regresoOrigenCPEFerroviariaDGAsync(IWscpeService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wscpe.RegresoOrigenCpeFerroviariaDgRequest validatedRequest, CancellationToken cancellationToken = default) => service.regresoOrigenCPEFerroviariaDGAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wscpe.RegresoOrigenCpeEmisionDestinoDgResponse> Wscpe_regresoOrigenCPEEmisionDestinoDGAsync(IWscpeService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wscpe.RegresoOrigenCpeEmisionDestinoDgRequest validatedRequest, CancellationToken cancellationToken = default) => service.regresoOrigenCPEEmisionDestinoDGAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wscpe.DesvioCpeAutomotorResponse> Wscpe_desvioCPEAutomotorAsync(IWscpeService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wscpe.DesvioCpeAutomotorRequest validatedRequest, CancellationToken cancellationToken = default) => service.desvioCPEAutomotorAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wscpe.ConfirmacionDefinitivaCpeAutomotorResponse> Wscpe_confirmacionDefinitivaCPEAutomotorAsync(IWscpeService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wscpe.ConfirmacionDefinitivaCpeAutomotorRequest validatedRequest, CancellationToken cancellationToken = default) => service.confirmacionDefinitivaCPEAutomotorAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wscpe.EditarCpeAutomotorResponse> Wscpe_editarCPEAutomotorAsync(IWscpeService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wscpe.EditarCpeAutomotorRequest validatedRequest, CancellationToken cancellationToken = default) => service.editarCPEAutomotorAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wscpe.EditarCpeConfirmadaAutomotorResponse> Wscpe_editarCPEConfirmadaAutomotorAsync(IWscpeService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wscpe.EditarCpeConfirmadaAutomotorRequest validatedRequest, CancellationToken cancellationToken = default) => service.editarCPEConfirmadaAutomotorAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wscpe.EditarCpeConfirmadaAutomotorDgResponse> Wscpe_editarCPEDGConfirmadaAutomotorAsync(IWscpeService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wscpe.EditarCpeConfirmadaAutomotorDgRequest validatedRequest, CancellationToken cancellationToken = default) => service.editarCPEDGConfirmadaAutomotorAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wscpe.EditarCpeConfirmadaFerroviariaDgResponse> Wscpe_editarCPEDGConfirmadaFerroviariaAsync(IWscpeService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wscpe.EditarCpeConfirmadaFerroviariaDgRequest validatedRequest, CancellationToken cancellationToken = default) => service.editarCPEDGConfirmadaFerroviariaAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wscpe.EditarCpeConfirmadaDuctosResponse> Wscpe_editarCPEConfirmadaDuctosAsync(IWscpeService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wscpe.EditarCpeConfirmadaDuctosRequest validatedRequest, CancellationToken cancellationToken = default) => service.editarCPEConfirmadaDuctosAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.Wscpe.ConsultarRenspaResponse> Wscpe_consultarRenspaAsync(IWscpeService service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.Wscpe.ConsultarRenspaRequest validatedRequest, CancellationToken cancellationToken = default) => service.consultarRenspaAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.PadronA4.DummyResponse> PadronA4_dummyAsync(IPadronA4Service service, ArcaEnvironment environment, CancellationToken cancellationToken = default) => service.dummyAsync(environment, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.PadronA4.GetPersonaResponse> PadronA4_getPersonaAsync(IPadronA4Service service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.PadronA4.GetPersona validatedRequest, CancellationToken cancellationToken = default) => service.getPersonaAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.PadronA5.GetPersonaResponse> PadronA5_getPersonaAsync(IPadronA5Service service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.PadronA5.GetPersona validatedRequest, CancellationToken cancellationToken = default) => service.getPersonaAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.PadronA5.GetPersonaListResponse> PadronA5_getPersonaListAsync(IPadronA5Service service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.PadronA5.GetPersonaList validatedRequest, CancellationToken cancellationToken = default) => service.getPersonaListAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.PadronA5.GetPersonaV2Response> PadronA5_getPersona_v2Async(IPadronA5Service service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.PadronA5.GetPersonaV2 validatedRequest, CancellationToken cancellationToken = default) => service.getPersona_v2Async(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.PadronA5.DummyResponse> PadronA5_dummyAsync(IPadronA5Service service, ArcaEnvironment environment, CancellationToken cancellationToken = default) => service.dummyAsync(environment, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.PadronA5.GetPersonaListV2Response> PadronA5_getPersonaList_v2Async(IPadronA5Service service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.PadronA5.GetPersonaListV2 validatedRequest, CancellationToken cancellationToken = default) => service.getPersonaList_v2Async(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.PadronA10.GetPersonaResponse> PadronA10_getPersonaAsync(IPadronA10Service service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.PadronA10.GetPersona validatedRequest, CancellationToken cancellationToken = default) => service.getPersonaAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.PadronA10.DummyResponse> PadronA10_dummyAsync(IPadronA10Service service, ArcaEnvironment environment, CancellationToken cancellationToken = default) => service.dummyAsync(environment, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.PadronA13.DummyResponse> PadronA13_dummyAsync(IPadronA13Service service, ArcaEnvironment environment, CancellationToken cancellationToken = default) => service.dummyAsync(environment, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.PadronA13.GetIdPersonaListByDocumentoResponse> PadronA13_getIdPersonaListByDocumentoAsync(IPadronA13Service service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.PadronA13.GetIdPersonaListByDocumento validatedRequest, CancellationToken cancellationToken = default) => service.getIdPersonaListByDocumentoAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.PadronA13.GetPersonaResponse> PadronA13_getPersonaAsync(IPadronA13Service service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.PadronA13.GetPersona validatedRequest, CancellationToken cancellationToken = default) => service.getPersonaAsync(tenant, validatedRequest, cancellationToken);

    public static Task<global::NetArcaWs.Contracts.PadronA13.GetPersonaV2Response> PadronA13_getPersonaV2Async(IPadronA13Service service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.PadronA13.GetPersonaV2 validatedRequest, CancellationToken cancellationToken = default) => service.getPersonaV2Async(tenant, validatedRequest, cancellationToken);

}
