<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <RestorePackagesWithLockFile>false</RestorePackagesWithLockFile>
    <PersistencePackageVersion Condition="'$(PersistencePackageVersion)' == ''">0.5.0</PersistencePackageVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NetArcaWs.EntityFrameworkCore" Version="$(PersistencePackageVersion)" />
    <PackageReference Include="NetArcaWs.EntityFrameworkCore.MySql" Version="$(PersistencePackageVersion)" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.12" />
  </ItemGroup>
</Project>
