// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetArcaWs.EntityFrameworkCore.Migrations.SqlServer;

#nullable disable

namespace NetArcaWs.EntityFrameworkCore.Migrations.SqlServer.Migrations.TenantCertificates
{
    [DbContext(typeof(SqlServerTenantCertificatesMigrationsDbContext))]
    partial class SqlServerTenantCertificatesMigrationsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("NetArcaWs:OptionsFingerprint", "342C0EAD67CF45DBC2AFC424EBE16AFF4F8215D268585F6C7EC0079611AFEFFD")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NetArcaWs.EntityFrameworkCore.ArcaCertificateSlotEntity", b =>
                {
                    b.Property<string>("TenantHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long>("Cuit")
                        .HasColumnType("bigint");

                    b.Property<int>("Environment")
                        .HasColumnType("int");

                    b.Property<Guid>("ActiveVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Generation")
                        .HasColumnType("bigint");

                    b.HasKey("TenantHash", "Cuit", "Environment");

                    b.ToTable("NetArcaCertificateSlots", "dbo");
                });

            modelBuilder.Entity("NetArcaWs.EntityFrameworkCore.ArcaCertificateVersionEntity", b =>
                {
                    b.Property<string>("TenantHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long>("Cuit")
                        .HasColumnType("bigint");

                    b.Property<int>("Environment")
                        .HasColumnType("int");

                    b.Property<Guid>("VersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Ciphertext")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<long>("CreatedAtUtcTicks")
                        .HasColumnType("bigint");

                    b.Property<string>("KeyId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<byte[]>("Nonce")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<long>("NotAfterUtcTicks")
                        .HasColumnType("bigint");

                    b.Property<long>("NotBeforeUtcTicks")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("Tag")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ThumbprintSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("TenantHash", "Cuit", "Environment", "VersionId");

                    b.HasIndex("TenantHash", "Cuit", "Environment", "NotAfterUtcTicks");

                    b.ToTable("NetArcaCertificateVersions", "dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
