// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetArcaWs.EntityFrameworkCore.Migrations.MariaDb;

#nullable disable

namespace NetArcaWs.EntityFrameworkCore.Migrations.MariaDb.Migrations.Invoicing
{
    [DbContext(typeof(MariaDbInvoicingMigrationsDbContext))]
    [Migration("20261006000100_InitialInvoicing")]
    partial class InitialInvoicing
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("NetArcaWs:OptionsFingerprint", "669F66786E519D34B365A818A008418C14A1AF2648F877B33E860D8A417B2B13")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("NetArcaWs.EntityFrameworkCore.InvoiceJournalEntity", b =>
                {
                    b.Property<string>("TenantHash")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("KeyHash")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("Attempt")
                        .HasColumnType("int");

                    b.Property<string>("AuthorizationCode")
                        .HasColumnType("longtext");

                    b.Property<int>("CanonicalVersion")
                        .HasColumnType("int");

                    b.Property<long>("CreatedUtcTicks")
                        .HasColumnType("bigint");

                    b.Property<long>("Cuit")
                        .HasColumnType("bigint");

                    b.Property<int>("Environment")
                        .HasColumnType("int");

                    b.Property<string>("FiscalHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<long?>("LeaseUntilMilliseconds")
                        .HasColumnType("bigint");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("PointOfSale")
                        .HasColumnType("int");

                    b.Property<string>("RemoteHash")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<long?>("RemoteRequestId")
                        .HasColumnType("bigint");

                    b.Property<string>("ResponseXml")
                        .HasColumnType("longtext");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ServiceHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.Property<long>("VoucherNumber")
                        .HasColumnType("bigint");

                    b.Property<int>("VoucherType")
                        .HasColumnType("int");

                    b.HasKey("TenantHash", "KeyHash");

                    b.HasIndex("FiscalHash")
                        .IsUnique()
                        .HasDatabaseName("UX_NetArcaInvoices_Fiscal");

                    b.HasIndex("RemoteHash")
                        .IsUnique()
                        .HasDatabaseName("UX_NetArcaInvoices_Remote");

                    b.HasIndex("TenantHash", "CreatedUtcTicks");

                    b.ToTable("NetArcaInvoices", (string)null);
                });

            modelBuilder.Entity("NetArcaWs.EntityFrameworkCore.InvoiceRevisionEntity", b =>
                {
                    b.Property<string>("TenantHash")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("KeyHash")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("int");

                    b.Property<int>("Attempt")
                        .HasColumnType("int");

                    b.Property<string>("AuthorizationCode")
                        .HasColumnType("longtext");

                    b.Property<int>("CanonicalVersion")
                        .HasColumnType("int");

                    b.Property<long>("Cuit")
                        .HasColumnType("bigint");

                    b.Property<int>("Environment")
                        .HasColumnType("int");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<long?>("LeaseUntilMilliseconds")
                        .HasColumnType("bigint");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("PointOfSale")
                        .HasColumnType("int");

                    b.Property<long?>("RemoteRequestId")
                        .HasColumnType("bigint");

                    b.Property<string>("ResponseXml")
                        .HasColumnType("longtext");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("SnapshotHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.Property<long>("VoucherNumber")
                        .HasColumnType("bigint");

                    b.Property<int>("VoucherType")
                        .HasColumnType("int");

                    b.HasKey("TenantHash", "KeyHash", "RevisionNumber");

                    b.ToTable("NetArcaInvoiceRevisions", (string)null);
                });

            modelBuilder.Entity("NetArcaWs.EntityFrameworkCore.InvoiceSeriesReservationEntity", b =>
                {
                    b.Property<string>("SeriesHash")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("TenantHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("SeriesHash");

                    b.HasIndex("TenantHash", "KeyHash")
                        .IsUnique();

                    b.ToTable("NetArcaInvoiceSeriesReservations", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
