// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetArcaWs.EntityFrameworkCore.Migrations.SqlServer;

#nullable disable

namespace NetArcaWs.EntityFrameworkCore.Migrations.SqlServer.Migrations.WsaaTickets
{
    [DbContext(typeof(SqlServerWsaaTicketsMigrationsDbContext))]
    partial class SqlServerWsaaTicketsMigrationsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("NetArcaWs:OptionsFingerprint", "2BC49A6100B69B909FC41163C7D7EC3D466E6D58680662800692AE00E46676BB")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NetArcaWs.EntityFrameworkCore.WsaaTicketEntity", b =>
                {
                    b.Property<string>("KeyHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("CertificateHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<byte[]>("Ciphertext")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<long?>("ExpiresUtcTicks")
                        .HasColumnType("bigint");

                    b.Property<long>("Fence")
                        .HasColumnType("bigint");

                    b.Property<string>("KeyId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<long?>("LeaseUntilUtcTicks")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("Nonce")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("OwnerId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<byte[]>("Tag")
                        .HasColumnType("varbinary(max)");

                    b.Property<long>("UpdatedUtcTicks")
                        .HasColumnType("bigint");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("KeyHash");

                    b.HasIndex("State", "UpdatedUtcTicks");

                    b.ToTable("NetArcaWsaaTickets", "dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
