// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetArcaWs.EntityFrameworkCore.Migrations.PostgreSql;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NetArcaWs.EntityFrameworkCore.Migrations.PostgreSql.Migrations.Invoicing
{
    [DbContext(typeof(PostgreSqlInvoicingMigrationsDbContext))]
    partial class PostgreSqlInvoicingMigrationsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("NetArcaWs:OptionsFingerprint", "669F66786E519D34B365A818A008418C14A1AF2648F877B33E860D8A417B2B13")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NetArcaWs.EntityFrameworkCore.InvoiceJournalEntity", b =>
                {
                    b.Property<string>("TenantHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("KeyHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Attempt")
                        .HasColumnType("integer");

                    b.Property<string>("AuthorizationCode")
                        .HasColumnType("text");

                    b.Property<int>("CanonicalVersion")
                        .HasColumnType("integer");

                    b.Property<long>("CreatedUtcTicks")
                        .HasColumnType("bigint");

                    b.Property<long>("Cuit")
                        .HasColumnType("bigint");

                    b.Property<int>("Environment")
                        .HasColumnType("integer");

                    b.Property<string>("FiscalHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long?>("LeaseUntilMilliseconds")
                        .HasColumnType("bigint");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("PointOfSale")
                        .HasColumnType("integer");

                    b.Property<string>("RemoteHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long?>("RemoteRequestId")
                        .HasColumnType("bigint");

                    b.Property<string>("ResponseXml")
                        .HasColumnType("text");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ServiceHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.Property<long>("VoucherNumber")
                        .HasColumnType("bigint");

                    b.Property<int>("VoucherType")
                        .HasColumnType("integer");

                    b.HasKey("TenantHash", "KeyHash");

                    b.HasIndex("FiscalHash")
                        .IsUnique()
                        .HasDatabaseName("UX_NetArcaInvoices_Fiscal");

                    b.HasIndex("RemoteHash")
                        .IsUnique()
                        .HasDatabaseName("UX_NetArcaInvoices_Remote");

                    b.HasIndex("TenantHash", "CreatedUtcTicks");

                    b.ToTable("NetArcaInvoices", "public");
                });

            modelBuilder.Entity("NetArcaWs.EntityFrameworkCore.InvoiceRevisionEntity", b =>
                {
                    b.Property<string>("TenantHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("KeyHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("integer");

                    b.Property<int>("Attempt")
                        .HasColumnType("integer");

                    b.Property<string>("AuthorizationCode")
                        .HasColumnType("text");

                    b.Property<int>("CanonicalVersion")
                        .HasColumnType("integer");

                    b.Property<long>("Cuit")
                        .HasColumnType("bigint");

                    b.Property<int>("Environment")
                        .HasColumnType("integer");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long?>("LeaseUntilMilliseconds")
                        .HasColumnType("bigint");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("PointOfSale")
                        .HasColumnType("integer");

                    b.Property<long?>("RemoteRequestId")
                        .HasColumnType("bigint");

                    b.Property<string>("ResponseXml")
                        .HasColumnType("text");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SnapshotHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.Property<long>("VoucherNumber")
                        .HasColumnType("bigint");

                    b.Property<int>("VoucherType")
                        .HasColumnType("integer");

                    b.HasKey("TenantHash", "KeyHash", "RevisionNumber");

                    b.ToTable("NetArcaInvoiceRevisions", "public");
                });

            modelBuilder.Entity("NetArcaWs.EntityFrameworkCore.InvoiceSeriesReservationEntity", b =>
                {
                    b.Property<string>("SeriesHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TenantHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("SeriesHash");

                    b.HasIndex("TenantHash", "KeyHash")
                        .IsUnique();

                    b.ToTable("NetArcaInvoiceSeriesReservations", "public");
                });
#pragma warning restore 612, 618
        }
    }
}
