// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetArcaWs.EntityFrameworkCore.Migrations.PostgreSql;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NetArcaWs.EntityFrameworkCore.Migrations.PostgreSql.Migrations.TenantCertificates
{
    [DbContext(typeof(PostgreSqlTenantCertificatesMigrationsDbContext))]
    partial class PostgreSqlTenantCertificatesMigrationsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("NetArcaWs:OptionsFingerprint", "342C0EAD67CF45DBC2AFC424EBE16AFF4F8215D268585F6C7EC0079611AFEFFD")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NetArcaWs.EntityFrameworkCore.ArcaCertificateSlotEntity", b =>
                {
                    b.Property<string>("TenantHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("Cuit")
                        .HasColumnType("bigint");

                    b.Property<int>("Environment")
                        .HasColumnType("integer");

                    b.Property<Guid>("ActiveVersionId")
                        .HasColumnType("uuid");

                    b.Property<long>("Generation")
                        .HasColumnType("bigint");

                    b.HasKey("TenantHash", "Cuit", "Environment");

                    b.ToTable("NetArcaCertificateSlots", "public");
                });

            modelBuilder.Entity("NetArcaWs.EntityFrameworkCore.ArcaCertificateVersionEntity", b =>
                {
                    b.Property<string>("TenantHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("Cuit")
                        .HasColumnType("bigint");

                    b.Property<int>("Environment")
                        .HasColumnType("integer");

                    b.Property<Guid>("VersionId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Ciphertext")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<long>("CreatedAtUtcTicks")
                        .HasColumnType("bigint");

                    b.Property<string>("KeyId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<byte[]>("Nonce")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<long>("NotAfterUtcTicks")
                        .HasColumnType("bigint");

                    b.Property<long>("NotBeforeUtcTicks")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("Tag")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("ThumbprintSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("TenantHash", "Cuit", "Environment", "VersionId");

                    b.HasIndex("TenantHash", "Cuit", "Environment", "NotAfterUtcTicks");

                    b.ToTable("NetArcaCertificateVersions", "public");
                });
#pragma warning restore 612, 618
        }
    }
}
