// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetArcaWs.EntityFrameworkCore.Migrations.Sqlite;

#nullable disable

namespace NetArcaWs.EntityFrameworkCore.Migrations.Sqlite.Migrations.WsaaTickets
{
    [DbContext(typeof(SqliteWsaaTicketsMigrationsDbContext))]
    partial class SqliteWsaaTicketsMigrationsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("NetArcaWs:OptionsFingerprint", "2BC49A6100B69B909FC41163C7D7EC3D466E6D58680662800692AE00E46676BB")
                .HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("NetArcaWs.EntityFrameworkCore.WsaaTicketEntity", b =>
                {
                    b.Property<string>("KeyHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("CertificateHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Ciphertext")
                        .HasColumnType("BLOB");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<long?>("ExpiresUtcTicks")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Fence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KeyId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long?>("LeaseUntilUtcTicks")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Nonce")
                        .HasColumnType("BLOB");

                    b.Property<string>("OwnerId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Tag")
                        .HasColumnType("BLOB");

                    b.Property<long>("UpdatedUtcTicks")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("KeyHash");

                    b.HasIndex("State", "UpdatedUtcTicks");

                    b.ToTable("NetArcaWsaaTickets", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
