// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetArcaWs.EntityFrameworkCore.Migrations.PostgreSql;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NetArcaWs.EntityFrameworkCore.Migrations.PostgreSql.Migrations.WsaaTickets
{
    [DbContext(typeof(PostgreSqlWsaaTicketsMigrationsDbContext))]
    [Migration("20261006000200_InitialWsaaTickets")]
    partial class InitialWsaaTickets
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("NetArcaWs:OptionsFingerprint", "2BC49A6100B69B909FC41163C7D7EC3D466E6D58680662800692AE00E46676BB")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NetArcaWs.EntityFrameworkCore.WsaaTicketEntity", b =>
                {
                    b.Property<string>("KeyHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("CertificateHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<byte[]>("Ciphertext")
                        .HasColumnType("bytea");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<long?>("ExpiresUtcTicks")
                        .HasColumnType("bigint");

                    b.Property<long>("Fence")
                        .HasColumnType("bigint");

                    b.Property<string>("KeyId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long?>("LeaseUntilUtcTicks")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("Nonce")
                        .HasColumnType("bytea");

                    b.Property<string>("OwnerId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<byte[]>("Tag")
                        .HasColumnType("bytea");

                    b.Property<long>("UpdatedUtcTicks")
                        .HasColumnType("bigint");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("KeyHash");

                    b.HasIndex("State", "UpdatedUtcTicks");

                    b.ToTable("NetArcaWsaaTickets", "public");
                });
#pragma warning restore 612, 618
        }
    }
}
