// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetArcaWs.EntityFrameworkCore.Migrations.Sqlite;

#nullable disable

namespace NetArcaWs.EntityFrameworkCore.Migrations.Sqlite.Migrations.InvoiceRecovery
{
    [DbContext(typeof(SqliteInvoiceRecoveryMigrationsDbContext))]
    partial class SqliteInvoiceRecoveryMigrationsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("NetArcaWs:OptionsFingerprint", "6FD40281D0B2769FD4032358EA8B18CE5D4D92EE042681A92964C2CE3F95B765")
                .HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("NetArcaWs.EntityFrameworkCore.InvoiceRecoveryJobEntity", b =>
                {
                    b.Property<string>("TenantHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("KeyHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Attempt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CanonicalVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("CredentialReference")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<long>("Cuit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Environment")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Generation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<long>("InvoiceVersion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LastReason")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LeaseUntilMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<long>("NextAvailableMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("PointOfSale")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<long>("VoucherNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VoucherType")
                        .HasColumnType("INTEGER");

                    b.HasKey("TenantHash", "KeyHash");

                    b.HasIndex("State", "NextAvailableMilliseconds", "LeaseUntilMilliseconds");

                    b.HasIndex("TenantHash", "Service", "NextAvailableMilliseconds");

                    b.ToTable("NetArcaInvoiceRecoveryJobs", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
