// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetArcaWs.EntityFrameworkCore.Migrations.SqlServer;

#nullable disable

namespace NetArcaWs.EntityFrameworkCore.Migrations.SqlServer.Migrations.InvoiceRecovery
{
    [DbContext(typeof(SqlServerInvoiceRecoveryMigrationsDbContext))]
    partial class SqlServerInvoiceRecoveryMigrationsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("NetArcaWs:OptionsFingerprint", "6FD40281D0B2769FD4032358EA8B18CE5D4D92EE042681A92964C2CE3F95B765")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NetArcaWs.EntityFrameworkCore.InvoiceRecoveryJobEntity", b =>
                {
                    b.Property<string>("TenantHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("KeyHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("Attempt")
                        .HasColumnType("int");

                    b.Property<int>("CanonicalVersion")
                        .HasColumnType("int");

                    b.Property<string>("ClaimId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("CredentialReference")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<long>("Cuit")
                        .HasColumnType("bigint");

                    b.Property<int>("Environment")
                        .HasColumnType("int");

                    b.Property<long>("Generation")
                        .HasColumnType("bigint");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<long>("InvoiceVersion")
                        .HasColumnType("bigint");

                    b.Property<int>("LastReason")
                        .HasColumnType("int");

                    b.Property<long?>("LeaseUntilMilliseconds")
                        .HasColumnType("bigint");

                    b.Property<long>("NextAvailableMilliseconds")
                        .HasColumnType("bigint");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("PointOfSale")
                        .HasColumnType("int");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<long>("VoucherNumber")
                        .HasColumnType("bigint");

                    b.Property<int>("VoucherType")
                        .HasColumnType("int");

                    b.HasKey("TenantHash", "KeyHash");

                    b.HasIndex("State", "NextAvailableMilliseconds", "LeaseUntilMilliseconds");

                    b.HasIndex("TenantHash", "Service", "NextAvailableMilliseconds");

                    b.ToTable("NetArcaInvoiceRecoveryJobs", "dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
