// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetArcaWs.EntityFrameworkCore.Migrations.MySql;

#nullable disable

namespace NetArcaWs.EntityFrameworkCore.Migrations.MySql.Migrations.TenantCertificates
{
    [DbContext(typeof(MySqlTenantCertificatesMigrationsDbContext))]
    [Migration("20261006000300_InitialTenantCertificates")]
    partial class InitialTenantCertificates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("NetArcaWs:OptionsFingerprint", "342C0EAD67CF45DBC2AFC424EBE16AFF4F8215D268585F6C7EC0079611AFEFFD")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("NetArcaWs.EntityFrameworkCore.ArcaCertificateSlotEntity", b =>
                {
                    b.Property<string>("TenantHash")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<long>("Cuit")
                        .HasColumnType("bigint");

                    b.Property<int>("Environment")
                        .HasColumnType("int");

                    b.Property<Guid>("ActiveVersionId")
                        .HasColumnType("char(36)");

                    b.Property<long>("Generation")
                        .HasColumnType("bigint");

                    b.HasKey("TenantHash", "Cuit", "Environment");

                    b.ToTable("NetArcaCertificateSlots", (string)null);
                });

            modelBuilder.Entity("NetArcaWs.EntityFrameworkCore.ArcaCertificateVersionEntity", b =>
                {
                    b.Property<string>("TenantHash")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<long>("Cuit")
                        .HasColumnType("bigint");

                    b.Property<int>("Environment")
                        .HasColumnType("int");

                    b.Property<Guid>("VersionId")
                        .HasColumnType("char(36)");

                    b.Property<byte[]>("Ciphertext")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<long>("CreatedAtUtcTicks")
                        .HasColumnType("bigint");

                    b.Property<string>("KeyId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<byte[]>("Nonce")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<long>("NotAfterUtcTicks")
                        .HasColumnType("bigint");

                    b.Property<long>("NotBeforeUtcTicks")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("Tag")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<string>("ThumbprintSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("TenantHash", "Cuit", "Environment", "VersionId");

                    b.HasIndex("TenantHash", "Cuit", "Environment", "NotAfterUtcTicks");

                    b.ToTable("NetArcaCertificateVersions", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
