using System.Text;
using System.Text.RegularExpressions;
using System.Xml.Linq;

namespace NetArcaWs.Build;

/// <summary>Builds the reference catalog and compileable, typed invocation adapters from the pinned contracts.</summary>
public static class OperationDocumentation
{
    private static readonly XNamespace Wsdl = "http://schemas.xmlsoap.org/wsdl/";
    private static readonly XNamespace Xsd = "http://www.w3.org/2001/XMLSchema";
    private static readonly XNamespace Soap = "http://schemas.xmlsoap.org/wsdl/soap/";
    private static readonly (string File, string Contract, string Client, string Wsaa)[] Services =
    [
        ("wsfev1-production.wsdl", "WsfeV1", "Wsfev1Service", "wsfe"),
        ("wsfexv1-production.wsdl", "WsfexV1", "Wsfexv1Service", "wsfex"),
        ("wsmtxca-production.wsdl", "Wsmtxca", "Wsmtxcav1Service", "wsmtxca"),
        ("padron-a4-production.wsdl", "PadronA4", "PadronA4Service", "ws_sr_padron_a4"),
        ("padron-a5-production.wsdl", "PadronA5", "PadronA5Service", "ws_sr_constancia_inscripcion"),
        ("padron-a10-production.wsdl", "PadronA10", "PadronA10Service", "ws_sr_padron_a10"),
        ("padron-a13-production.wsdl", "PadronA13", "PadronA13Service", "ws_sr_padron_a13")
    ];

    public static void Run(string root)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(root);
        root = Path.GetFullPath(root);
        var contractDir = Path.Combine(root, "docs", "reference", "contracts");
        var serviceSource = File.ReadAllText(Path.Combine(root, "src", "NetArcaWs", "Services", "Generated", "ArcaServices.g.cs"));
        var docsDir = Path.Combine(root, "docs", "reference", "operations");
        var exampleDir = Path.Combine(root, "examples", "NetArcaWs.Examples");
        Directory.CreateDirectory(docsDir);
        Directory.CreateDirectory(exampleDir);
        var allExamples = new StringBuilder("// <auto-generated>Generated from pinned WSDLs; pass consumer-validated payloads.</auto-generated>\n#nullable enable\nusing System.Threading;\nusing System.Threading.Tasks;\nusing NetArcaWs.Multitenancy;\nusing NetArcaWs.Services;\nusing NetArcaWs.HealthChecks;\n\nnamespace NetArcaWs.Examples;\n\n/// <summary>Typed forwarding adapters. The caller supplies validated request data; this catalog creates no incomplete DTOs and submits no operation itself.</summary>\npublic static class OperationExamples\n{\n");
        var total = 0;
        foreach (var service in Services)
        {
            var path = Path.Combine(contractDir, service.File);
            if (!File.Exists(path)) throw new InvalidOperationException($"Pinned WSDL missing: {path}");
            var wsdl = XDocument.Load(path);
            var schema = wsdl.Descendants(Xsd + "schema").FirstOrDefault() ?? throw new InvalidOperationException($"{service.File}: no inline schema");
            var ns = (string?)schema.Attribute("targetNamespace") ?? "";
            var operations = ParseOperations(wsdl, serviceSource, service);
            total += operations.Count;
            File.WriteAllText(Path.Combine(docsDir, service.Contract.ToLowerInvariant() + ".md"), RenderService(service, ns, schema, operations), new UTF8Encoding(false));
            RenderExamples(allExamples, service, operations);
        }
        if (total != 81) throw new InvalidOperationException($"Expected 81 WSDL operations, found {total}.");
        allExamples.AppendLine("}");
        File.WriteAllText(Path.Combine(exampleDir, "OperationExamples.g.cs"), allExamples.ToString(), new UTF8Encoding(false));
        File.WriteAllText(Path.Combine(exampleDir, "NetArcaWs.Examples.csproj"), """
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net10.0</TargetFramework><IsPackable>false</IsPackable>
    <Nullable>enable</Nullable><ImplicitUsings>enable</ImplicitUsings></PropertyGroup>
  <ItemGroup><ProjectReference Include="../../src/NetArcaWs/NetArcaWs.csproj" /></ItemGroup>
</Project>
""" + "\n", new UTF8Encoding(false));
    }

    private sealed record Op(string Name, string RequestRoot, string ResponseRoot, string RequestType, string ResponseType, string Action, bool Dummy);

    private static List<Op> ParseOperations(XDocument wsdl, string source, (string File, string Contract, string Client, string Wsaa) service)
    {
        var messageMap = wsdl.Root!.Elements(Wsdl + "message").ToDictionary(x => (string)x.Attribute("name")!, StringComparer.Ordinal);
        var actionMap = wsdl.Root.Elements(Wsdl + "binding").Where(x => x.Element(Soap + "binding") is not null)
            .SelectMany(x => x.Elements(Wsdl + "operation")).ToDictionary(x => (string)x.Attribute("name")!, x => (string?)x.Element(Soap + "operation")?.Attribute("soapAction") ?? "", StringComparer.Ordinal);
        var interfaces = Regex.Match(source, $"public interface I{Regex.Escape(service.Client)}\\s*\\{{(?<body>.*?)\\n\\}}", RegexOptions.Singleline).Groups["body"].Value;
        var sigs = new Dictionary<string, (string Req, string Res)>(StringComparer.Ordinal);
        foreach (var line in interfaces.Split('\n'))
        {
            var m = Regex.Match(line, @"Task<global::NetArcaWs\.Contracts\.[^.]+\.(?<response>\w+)>\s+(?<method>\w+)\((?<args>.*?)\);", RegexOptions.CultureInvariant);
            if (!m.Success) continue;
            var request = Regex.Match(m.Groups["args"].Value, @"global::NetArcaWs\.Contracts\.[^.]+\.(?<type>\w+) request", RegexOptions.CultureInvariant);
            sigs[m.Groups["method"].Value.Replace("Async", "", StringComparison.Ordinal)] = (request.Success ? request.Groups["type"].Value : "", m.Groups["response"].Value);
        }
        var result = new List<Op>();
        foreach (var operation in wsdl.Root.Element(Wsdl + "portType")!.Elements(Wsdl + "operation"))
        {
            var name = (string)operation.Attribute("name")!;
            var input = operation.Element(Wsdl + "input")!; var output = operation.Element(Wsdl + "output")!;
            var reqMessage = messageMap[Local((string)input.Attribute("message")!)];
            var resMessage = messageMap[Local((string)output.Attribute("message")!)];
            var reqRoot = (string?)reqMessage.Element(Wsdl + "part")?.Attribute("element") ?? "(vacío)";
            var resRoot = (string?)resMessage.Element(Wsdl + "part")?.Attribute("element") ?? throw new InvalidOperationException($"{name}: missing output element");
            var dummy = name.Contains("dummy", StringComparison.OrdinalIgnoreCase);
            var sig = sigs.TryGetValue(name, out var found) ? found : (Req: "", Res: "");
            var requestType = dummy ? "" : sig.Req;
            var responseType = sig.Res;
            if (responseType.Length == 0 || (!dummy && requestType.Length == 0)) throw new InvalidOperationException($"{service.Contract}.{name}: generated C# signature missing");
            result.Add(new Op(name, Local(reqRoot), Local(resRoot), requestType, responseType, actionMap.GetValueOrDefault(name, ""), dummy));
        }
        return result;
    }

    private static string RenderService((string File, string Contract, string Client, string Wsaa) svc, string ns, XElement schema, List<Op> ops)
    {
        var info = ServiceInfo(svc.Contract);
        var b = new StringBuilder($"# {svc.Contract} — operaciones SOAP\n\nContrato generado desde [`{svc.File}`](../contracts/{svc.File}); namespace XML `{ns}`. El servicio WSAA es `{svc.Wsaa}`. Las operaciones autenticadas envían ticket WSAA; `dummy` es una comprobación no autenticada según el cliente generado.\n\nLos tipos C# indicados proceden de los contratos generados y el WSDL fijado. `minOccurs`, `maxOccurs` y `nillable` describen estructura XML; **no sustituyen reglas de negocio** ni garantizan aceptación por ARCA. No se inventan validaciones de negocio.\n\n| Operación | Clase | Request C# | Response C# | SOAPAction |\n|---|---|---|---|---|\n");
        foreach (var op in ops) b.AppendLine($"| `{op.Name}` | {(op.Dummy ? "consulta técnica, sin WSAA" : "requiere ticket WSAA") } | {(op.Dummy ? "sin DTO" : $"`{svc.Contract}.{op.RequestType}`")} | `{svc.Contract}.{op.ResponseType}` | `{Escape(op.Action)}` |");
        b.AppendLine("\n## Campos y tipos\n\nCada tabla lista los campos XML del elemento raíz de request/response. Las referencias a tipos nombrados se amplían en el catálogo de tipos complejos. Para respuestas, `Errors`/`Observaciones` (cuando el tipo los declara) transportan rechazos y avisos del servicio; las tablas de errores ARCA por código deben contrastarse con el manual vigente del servicio. Un SOAP Fault de transporte/protocolo se expone como `NetArcaWs.Transport.SoapFaultException` con `Code`, `Reason`, `Detail` y `StatusCode`. No reintentar automáticamente escrituras: ante timeout o resultado incierto, reconciliar el estado antes de cualquier nuevo envío.\n");
        foreach (var op in ops)
        {
            b.AppendLine($"\n### `{op.Name}`\n\nClase: **{(op.Dummy ? "consulta técnica" : IsWrite(op.Name) ? "escritura" : "consulta") }**; autenticación: **{(op.Dummy ? "no requiere ticket WSAA" : $"WSAA `{svc.Wsaa}`") }**. SOAPAction: `{Escape(op.Action)}`.\n");
            b.AppendLine("**Request** (`" + (op.Dummy ? "sin elemento/payload" : svc.Contract + "." + op.RequestType) + "`, raíz XML `" + op.RequestRoot + "`)\n");
            if (!op.Dummy) RenderFields(b, schema, op.RequestRoot);
            b.AppendLine("\n**Response** (`" + svc.Contract + "." + op.ResponseType + "`, raíz XML `" + op.ResponseRoot + "`)\n");
            RenderFields(b, schema, op.ResponseRoot);
            b.AppendLine($"\n{ErrorDescription(svc.Contract)} SOAP Fault: `NetArcaWs.Transport.SoapFaultException` expone código, razón, detalle y estado HTTP. Para escrituras, no repetir automáticamente tras fallo ambiguo; consultar/reconciliar primero.\n");
        }
        b.AppendLine("\n## Catálogo de tipos complejos\n\nIncluye todos los tipos complejos nombrados del XSD del servicio. Los elementos `base` señalan herencia; se conserva la cardinalidad declarada. `xs:documentation` se transcribe cuando existe.\n");
        foreach (var type in schema.Elements(Xsd + "complexType").Where(x => x.Attribute("name") is not null).OrderBy(x => (string)x.Attribute("name")!, StringComparer.Ordinal))
        {
            var name = (string)type.Attribute("name")!;
            b.AppendLine($"\n### `{name}`\n");
            var baseType = type.Descendants(Xsd + "extension").Select(x => (string?)x.Attribute("base")).FirstOrDefault(x => x is not null);
            if (baseType is not null) b.AppendLine($"Extiende `{Local(baseType)}`.\n");
            RenderFields(b, schema, name);
        }
        var details = ServiceInfo(svc.Contract);
        return b.ToString()
            .Replace($"# {svc.Contract} — operaciones SOAP", $"# {details.Title}", StringComparison.Ordinal)
            .Replace("\n\nContrato generado", $"\n\n**Rol:** {details.Role}\n\n**Funcionalidad:** {details.Functionality}\n\n**Uso:** {details.Usage}\n\nContrato generado", StringComparison.Ordinal)
            .Replace("\n\n| Operación | Clase |", "\n\n## Operaciones disponibles\n\n| Operación | Clase |", StringComparison.Ordinal);
    }

    private static void RenderFields(StringBuilder b, XElement schema, string rootName)
    {
        var element = schema.Elements(Xsd + "element").FirstOrDefault(x => (string?)x.Attribute("name") == rootName);
        var type = schema.Elements(Xsd + "complexType").FirstOrDefault(x => (string?)x.Attribute("name") == rootName);
        var complex = element?.Element(Xsd + "complexType") ?? type;
        var fields = complex is null ? null : DirectFields(complex);
        if (fields is null || !fields.Any()) { b.AppendLine("El tipo no declara elementos hijo directos en el XSD; puede ser vacío o derivar su contenido de un tipo base, que se documenta por separado."); return; }
        b.AppendLine("| Campo | Tipo XSD | minOccurs | maxOccurs | nillable | Requerido por XSD | Documentación XSD |\n|---|---|---:|---:|---|---|---|");
        foreach (var f in fields)
        {
            var min = (string?)f.Attribute("minOccurs") ?? "1"; var max = (string?)f.Attribute("maxOccurs") ?? "1";
            var typeName = (string?)f.Attribute("type") ?? (f.Element(Xsd + "complexType") is not null ? "(complejo anónimo)" : "(tipo local)");
            var documentation = string.Join(" ", f.Descendants(Xsd + "documentation").Select(x => x.Value.Trim()).Where(x => x.Length > 0));
            var renderedType = typeName.StartsWith("tns:", StringComparison.Ordinal) ? $"[`{typeName}`](#{Local(typeName).ToLowerInvariant()})" : $"`{typeName}`";
            b.AppendLine($"| `{(string?)f.Attribute("name") ?? (string?)f.Attribute("ref") ?? "(sin nombre)"}` | {renderedType} | {min} | {max} | {(string?)f.Attribute("nillable") ?? "false"} | {(min == "0" ? "No" : "Sí")}; el esquema no valida reglas de negocio | {Escape(documentation)} |");
        }
        var attributes = complex is null ? [] : DirectAttributes(complex).ToArray();
        if (attributes.Length > 0)
        {
            b.AppendLine("\nAtributos XSD:\n\n| Atributo | Tipo XSD | Uso | Requerido por XSD | Documentación XSD |\n|---|---|---|---|---|");
            foreach (var attribute in attributes)
            {
                var required = (string?)attribute.Attribute("use") == "required";
                var attrType = (string?)attribute.Attribute("type") ?? "(tipo local)";
                var attrDoc = string.Join(" ", attribute.Descendants(Xsd + "documentation").Select(x => x.Value.Trim()).Where(x => x.Length > 0));
                b.AppendLine($"| `{(string?)attribute.Attribute("name") ?? "(sin nombre)"}` | `{attrType}` | {(required ? "required" : (string?)attribute.Attribute("use") ?? "optional")} | {(required ? "Sí" : "No")} | {Escape(attrDoc)} |");
            }
        }
    }

    private static IEnumerable<XElement> DirectFields(XElement complex)
    {
        var compositor = complex.Elements().Where(x => x.Name == Xsd + "sequence" || x.Name == Xsd + "all" || x.Name == Xsd + "choice");
        foreach (var group in complex.Elements(Xsd + "complexContent").Elements(Xsd + "extension").SelectMany(x => x.Elements()))
            if (group.Name == Xsd + "sequence" || group.Name == Xsd + "all" || group.Name == Xsd + "choice") compositor = compositor.Append(group);
        return compositor.SelectMany(x => x.Elements(Xsd + "element"));
    }

    private static IEnumerable<XElement> DirectAttributes(XElement complex)
    {
        return complex.Elements(Xsd + "attribute").Concat(
            complex.Elements(Xsd + "complexContent").Elements(Xsd + "extension").Elements(Xsd + "attribute"));
    }

    private static void RenderExamples(StringBuilder b, (string File, string Contract, string Client, string Wsaa) svc, List<Op> ops)
    {
        foreach (var op in ops)
        {
            var methodName = Regex.Replace(svc.Contract + "_" + op.Name, "[^A-Za-z0-9_]", "_");
            if (op.Dummy)
                b.AppendLine($"    public static Task<global::NetArcaWs.Contracts.{svc.Contract}.{op.ResponseType}> {methodName}Async(I{svc.Client} service, ArcaEnvironment environment, CancellationToken cancellationToken = default) => service.{op.Name}Async(environment, cancellationToken);\n");
            else
                b.AppendLine($"    public static Task<global::NetArcaWs.Contracts.{svc.Contract}.{op.ResponseType}> {methodName}Async(I{svc.Client} service, ArcaTenantContext tenant, global::NetArcaWs.Contracts.{svc.Contract}.{op.RequestType} validatedRequest, CancellationToken cancellationToken = default) => service.{op.Name}Async(tenant, validatedRequest, cancellationToken);\n");
        }
    }

    private static string ErrorDescription(string contract) => contract switch
    {
        "WsfeV1" => "Errores funcionales WSFE se devuelven en `Errors` (tipo `Err`, campos `Code` y `Msg`); los avisos van en `Observaciones` (tipo `Obs`).",
        "WsfexV1" => "El resultado WSFEX incluye `FEXErr` (`ErrCode`, `ErrMsg`) y, según la operación, `Obs`/`Obs_comerciales`; revisar también el resultado de autorización devuelto.",
        "Wsmtxca" => "Las respuestas WSMTXCA exponen `resultado` y, según operación, `arrayErrores` y `arrayObservaciones` como códigos y descripciones; interpretar sus valores con el manual vigente.",
        _ => "Los WSDL de Padrón declaran `SRValidationException` como fault SOAP de servicio; su estructura aparece en el catálogo XSD y los errores no se expresan como `Errors` dentro de un resultado normal."
    };

    private sealed record ServiceDetails(string Title, string Role, string Functionality, string Usage);

    private static ServiceDetails ServiceInfo(string contract) => contract switch
    {
        "WsfeV1" => new("WSFEv1: facturación nacional", "Emisión electrónica de comprobantes del mercado interno.", "Autorizar comprobantes, consultar comprobantes y CAEA, y leer parámetros de facturación.", "Integrarlo en el flujo de facturación nacional; proteger las escrituras con persistencia e idempotencia en la aplicación consumidora."),
        "WsfexV1" => new("WSFEXv1: facturación de exportación", "Emisión electrónica de comprobantes de exportación.", "Autorizar y consultar comprobantes de exportación, obtener último número y consultar parámetros.", "Usarlo en el circuito de exportación con datos aduaneros y comerciales validados por el sistema consumidor."),
        "Wsmtxca" => new("WSMTXCA: factura electrónica", "Servicio de factura electrónica con operaciones de autorización y consulta.", "Autorizar comprobantes y ajustes, informar CAEA y consultar catálogos, estados y comprobantes.", "Elegir las operaciones según el circuito habilitado para el contribuyente y validar los códigos de resultado con el manual vigente."),
        "PadronA4" => new("Padrón A4: consulta de persona", "Consulta de datos registrales de una persona.", "Consultar una persona por CUIT representada y persona consultada.", "Usarlo como consulta registral autenticada; el WSDL declara faults de validación del padrón."),
        "PadronA5" => new("Padrón A5: constancia de inscripción", "Consulta de constancia y datos de inscripción.", "Consultar personas y listas, con variantes de respuesta v2.", "Usarlo para recuperar datos de inscripción; verificar en el manual la variante adecuada y tratar faults `SRValidationException`."),
        "PadronA10" => new("Padrón A10: consulta registral", "Consulta individual del padrón A10.", "Consultar datos de una persona y comprobar disponibilidad técnica.", "Usarlo como lectura autenticada y tratar faults `SRValidationException`."),
        _ => new("Padrón A13: búsqueda y consulta de persona", "Búsqueda de identidad y consulta de datos registrales.", "Buscar identificadores por documento y consultar personas, incluidas respuestas v2.", "Usarlo para búsquedas y lecturas autenticadas; tratar faults `SRValidationException`.")
    };

    private static bool IsWrite(string name) => Regex.IsMatch(name, "solicitar|informar|informativ|registrar|autorizar|authorize|emitir|anular|baja|alta|modificar|actualizar|asociar|insertar|grabar", RegexOptions.IgnoreCase | RegexOptions.CultureInvariant);
    private static string Local(string qname) => qname[(qname.LastIndexOf(':') + 1)..];
    private static string Escape(string text) => text.Replace("|", "\\|").Replace("\r", " ").Replace("\n", " ");
}
